# Generated by Django 3.2 on 2024-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=50)),
                ('sbranch', models.CharField(default='CSE', max_length=10)),
                ('syear', models.IntegerField(default=1)),
            ],
        ),
    ]
